### ISSUE TITLE
Error when accessing some player's page

### ISSUE THREAD

**Issue by CNA0086** [SakuraIsayeki/WOWS-Karma#84] opened 2022-03-20 15:04 UTC
This error occurred when accessing the wows karma page from the wows-monitor program provided links for some players. The first log is for my account and the next one is just a random opponent who did poorly in the game. I thought it was the "\_" in both of our names but some other players with the same "\_" have a perfectly working page. I will leave the rest to you guys.

https://na.wows-karma.com/player/1049454182,Player_1159465670/
```
API Request: https://api.na.wows-karma.com:80/api/player/1049454182

WowsKarma.Web.Infrastructure.Exceptions.ApiErrorResponseException: System.Text.Json.JsonException: The JSON value could not be converted to System.Int64. Path: $.clanview.wows_ladder.members_count | LineNumber: 0 | BytePositionInLine: 502.
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Nodsoft.Wargaming.Api.Client.Clients.Wows.WowsClansApiClient.FetchClanViewAsync(UInt32 clanId, CancellationToken ct)
   at WowsKarma.Api.Services.ClanService.UpdateClanInfoAsync(ApiDbContext context, UInt32 clanId, Clan clan, CancellationToken ct) in D:\Code\Source\WoWS-Karma\WowsKarma.Api\Services\ClanService.cs:line 84
   at WowsKarma.Api.Services.PlayerService.UpdatePlayerClanStatusAsync(Player player, CancellationToken ct) in D:\Code\Source\WoWS-Karma\WowsKarma.Api\Services\PlayerService.cs:line 174
   at WowsKarma.Api.Services.PlayerService.GetPlayerAsync(UInt32 accountId, Boolean includeRelated, Boolean includeClanInfo, CancellationToken ct) in D:\Code\Source\WoWS-Karma\WowsKarma.Api\Services\PlayerService.cs:line 96
   at WowsKarma.Api.Controllers.PlayerController.GetAccount(UInt32 id, Boolean includeClanInfo) in D:\Code\Source\WoWS-Karma\WowsKarma.Api\Controllers\PlayerController.cs:line 59
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WowsKarma.Api.Middlewares.RequestLoggingMiddleware.Invoke(HttpContext context) in D:\Code\Source\WoWS-Karma\WowsKarma.Api\Middlewares\RequestLoggingMiddleware.cs:line 49
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```
https://na.wows-karma.com/player/1026846969,Slimy_Muppet/
```
API Request: https://api.na.wows-karma.com:80/api/player/1026846969

WowsKarma.Web.Infrastructure.Exceptions.ApiErrorResponseException: System.Text.Json.JsonException: The JSON value could not be converted to System.Int64. Path: $.clanview.wows_ladder.members_count | LineNumber: 0 | BytePositionInLine: 803.
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonConverter converter, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.ReadAllAsync[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)
   at System.Net.Http.Json.HttpContentJsonExtensions.ReadFromJsonAsyncCore[T](HttpContent content, Encoding sourceEncoding, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Nodsoft.Wargaming.Api.Client.Clients.Wows.WowsClansApiClient.FetchClanViewAsync(UInt32 clanId, CancellationToken ct)
   at WowsKarma.Api.Services.ClanService.UpdateClanInfoAsync(ApiDbContext context, UInt32 clanId, Clan clan, CancellationToken ct) in D:\Code\Source\WoWS-Karma\WowsKarma.Api\Services\ClanService.cs:line 84
   at WowsKarma.Api.Services.PlayerService.UpdatePlayerClanStatusAsync(Player player, CancellationToken ct) in D:\Code\Source\WoWS-Karma\WowsKarma.Api\Services\PlayerService.cs:line 174
   at WowsKarma.Api.Services.PlayerService.GetPlayerAsync(UInt32 accountId, Boolean includeRelated, Boolean includeClanInfo, CancellationToken ct) in D:\Code\Source\WoWS-Karma\WowsKarma.Api\Services\PlayerService.cs:line 96
   at WowsKarma.Api.Controllers.PlayerController.GetAccount(UInt32 id, Boolean includeClanInfo) in D:\Code\Source\WoWS-Karma\WowsKarma.Api\Controllers\PlayerController.cs:line 59
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WowsKarma.Api.Middlewares.RequestLoggingMiddleware.Invoke(HttpContext context) in D:\Code\Source\WoWS-Karma\WowsKarma.Api\Middlewares\RequestLoggingMiddleware.cs:line 49
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```

**Comment by SakuraIsayeki** [comment] 2022-03-20 15:06
Acknowledged issue. Duplicate of #82, but more complete stacktraces

**Comment by SakuraIsayeki** [comment] 2022-03-26 10:18
Closing issue as duplicate of #82. Will be focusing all efforts on that issue instead.

**Closed by SakuraIsayeki** 2022-03-26 10:18 UTC
Labels: bug
